#!python
import sys
from PIL import Image
import numpy as np
import argparse

#######################
### Parse arguments ###
#######################
parser = argparse.ArgumentParser(
  prog = 'Viz',
  description = 'Visualize data',
)
parser.add_argument(
  '--format',
  type=str,
  help='Input Format (not implemented)',
  required=True,
  choices=['csv'],
)
parser.add_argument(
  '--type',
  type=str,
  help='Output type (not implemented)',
  required=True,
  choices=['png', 'gif'],
)
parser.add_argument(
  '--width',
  type=int,
  required=True,
  help='Width (not implemented)',
)
parser.add_argument(
  '--height',
  type=int,
  required=True,
  help='Height (not implemented)',
)
parser.add_argument(
  '--color',
  action='store_true',
  help='Color (not implemented)',
)
parser.add_argument(
  '--speed',
  type=int,
  default=100,
  help='Gif speed (ms) (not implemented)',
  required=False,
)

args = parser.parse_args()

#######################
######## Util #########
#######################

def parse_csv(data):
  """
  Parse a csv file
  """
  Exception('Not implemented')

def data_to_png(data):
  """
  Convert a matrix to an image
  """
  Exception('Not implemented')

def data_to_gif(data):
  """
  Convert a 3D matrix to a gif
  """
  Exception('Not implemented')